### ISSUE TITLE
refactor on VAT ID

### ISSUE THREAD

**Issue by wojosc** [imat-open-source/German-Accounting#13]
The customer has applied a VAT ID field on Customer DocType with the fieldname `vatid`. It is a data field. This should not be part of the app but concidered in further developments.

Please add the field `vatid` on DocType Address and Customer but only in the case if it does not already exist.

The following checkbox is not actually needed for the user to see. It is only used for the validation.
![grafik](https://github.com/imat-open-source/German-Accounting/assets/22279621/14e8080b-952e-4a83-8917-c93587d2c48f)

For the moment we are assuming, that the VAT ID of a customer is valid in case it exists. If the field ist left blank in the masters we assume, that the customer has no valid VAT ID.

Further this field will not be needed:
![grafik](https://github.com/imat-open-source/German-Accounting/assets/22279621/9ce41ab4-b58d-4622-9ae8-5a8c0af7993c)

The print is only necessary on the actual Print Format.

**Comment by beingeek** [comment]
Should i hide field Print Vat Display and can only be showen in print format

**Comment by wojosc** [comment]
the transaction will have a `vatid` field. The "Print Vat Display" will be covered via logic in Print Format.
