### ISSUE TITLE
Remove Destination

### ISSUE THREAD

**Issue by wojosc** [imat-open-source/German-Accounting#14]
The Destination selection is not necessary. This can be done by using Tax Categories. These need to be setup in the systems to use to test and will have the same options. These options will be chosen opon Tax Rules that need to be set up.

In case the following field is used in some code we will need to discuss how this can be done using Tax Category

![grafik](https://github.com/imat-open-source/German-Accounting/assets/22279621/07e724fb-8055-455a-a459-784c299b166a)

**Comment by beingeek** [comment]
Destination selection as we discussed previously should be in system setting, possibly a configuration where we can map Tax Category with these 3 options in select field. 

![image](https://github.com/imat-open-source/German-Accounting/assets/25414115/6348a4a1-a962-4305-9630-437499b13308)

**Comment by wojosc** [comment]
was removed in favour of Tax Categories https://doku.phamos.eu/books/erpnext-benutzerhandbuch/page/steuerkategorie-tax-category
