### ISSUE TITLE
Jinja-Code for Tax Logic in Print Format

### ISSUE THREAD

**Issue by wojosc** [imat-open-source/German-Accounting#17]
The following Jinja-Code represents the logic used to show the Tax- Print correctly on a Transaction. The code was created on Quotation and might have to be modified for later documents (Sales Order, Sales Invoice etc.)

https://github.com/imat-open-source/German-Accounting/issues/17#issuecomment-1791447212

**Comment by beingeek** [comment]
<h2>
    <p>Tax Category: {{ doc.tax_category }}</p>
    <p>Item Group: {{ doc.item_group }}</p>
    
    {% if doc.customer_address and doc.item_group %}
    
        
        {% set customer = frappe.get_doc("Customer", doc.party_name) %}
        <p>VATID: {{ doc.vat_id if doc.vat_id else 'not set' }}</p>
        
        
        
        {% if doc.tax_category == "Germany (Umsatzsteuer)" %}
            {% if doc.item_group == "Goods" %}
                <p>19 % VAT</p>
            {% elif doc.item_group == "Services" %}
                <p>19 % VAT</p>
            {% endif %}
        {% endif %}
        
        
        
        {% if doc.tax_category == "Non-EU Country" %}
            {% if doc.item_group == "Goods" %}
                <p>0% VAT, VAT-free export delivery</p>
            {% elif doc.item_group == "Services" %}            
                {% if customer.customer_type == 'Individual' %}
                    <p>0% VAT, service non-taxable domestically</p>
                {% else %}
                    <p>19 % VAT</p>
                {% endif %}  
                
                
            {% endif %}
        {% endif %}
        
        
        
        {% if doc.tax_category == "EU Country" %}
            {% if doc.item_group == "Goods" %}
                {% if doc.vat_id %}
                    <p>0% VAT, tax-free intra-community supply</p>
                {% else %}
                    <p>19 % VAT</p>
                {% endif %}  
            {% elif doc.item_group == "Services" %}
                {% if doc.vat_id %}
                    <p>0% VAT, tax-free intra-community service (reverse charge procedure)</p>
                {% else %}
                    <p>19 % VAT</p>
                {% endif %}  
            {% endif %}
        {% endif %}
    {% endif %}
    
    {% if not doc.item_group %}
        <p>Item Group not set</p>
    {% endif %}
    
    {% if not doc.customer_address %}
        <p>Customer Address not set</p>
    {% endif %}

</h2>

**Comment by wojosc** [comment]
https://imat-uve.phamos.eu/books/erpnext-handbuch/page/quotation
